---
    - name: Generate SSH keys
      shell: "ssh-keygen -q -t rsa -f {{ installer_home }}/.ssh/id_rsa -N ''"
      args:
        creates: "{{ installer_home }}/.ssh/id_rsa"

    - name: Retrieve id_rsa.pub
      shell: "/bin/cat {{ installer_home }}/.ssh/id_rsa.pub"
      register: ssh_key

    - name: Set public key
      set_fact:
        ssh_key: "{{ssh_key.stdout}}"

    - debug:
        var: hostvars[item]
      with_items: "{{ groups['vertica'] }}"
      when: yes

    - name: Remove known_hosts
      file:
        path: "{{ installer_home }}/.ssh/known_hosts"
        state: absent
      when: force

    - name: Remove authorized_keys
      file:
        path: "{{ installer_home }}/.ssh/authorized_keys"
        state: absent
      when: force

    - name: Store cluster node public keys in authorized_keys
      lineinfile:
        dest: "{{ installer_home }}/.ssh/authorized_keys"
        state: present
        create: yes
        line: "{{ hostvars[item]['ssh_key'] }}"
      with_items: "{{ groups['vertica'] }}"


